# Generated by Django 5.1 on 2025-04-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_job_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='content',
            field=models.TextField(),
        ),
    ]
