# Generated by Django 5.1 on 2025-04-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_user_organization_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
