# Generated by Django 5.1 on 2025-05-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/'),
        ),
    ]
