# Generated by Django 5.1 on 2025-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_product_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
